[package]
name = "wasm-path-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"]}
wasm-bindgen = "0.2.87"
# I need logging
log = "0.4.6"
wasm-logger = "0.2.0"

[dependencies.web-sys]
version = "0.3.64"
features = [
    "HtmlSelectElement"
]